import prisma from "../config/prisma.js";

async function seedAllJobs() {
  console.log("🌱 Seeding 20 jobs...");

  const jobs = [
    {
      title: "Software Developer 3",
      company: "Oracle",
      description: "Design and develop scalable cloud-native applications.",
      type: "Full-time",
      experience: "3-5 years",
      location: "Bengaluru, Karnataka",
      isRemote: false,
      tags: ["Java", "Cloud", "OCI", "Microservices"],
    },
    {
      title: "Senior Software Engineer",
      company: "Google",
      description: "Build large-scale distributed systems.",
      type: "Full-time",
      experience: "5+ years",
      location: "Bengaluru, Karnataka",
      isRemote: true,
      tags: ["Python", "Go", "Distributed Systems"],
    },
    {
      title: "Lead Software Engineer - Backend",
      company: "Salesforce",
      description: "Lead backend architecture for Salesforce products.",
      type: "Full-time",
      experience: "5+ years",
      location: "Bengaluru, Karnataka",
      isRemote: true,
      tags: ["Java", "Scala", "AWS"],
    },
    {
      title: "Software Development Intern",
      company: "Internshala",
      description: "Work on real-world web applications.",
      type: "Internship",
      experience: "0-1 years",
      location: "Work From Home",
      isRemote: true,
      tags: ["React", "Node.js", "MongoDB"],
    },
    {
      title: "Web Development Intern",
      company: "Internshala",
      description: "Develop responsive web pages.",
      type: "Internship",
      experience: "0-1 years",
      location: "Work From Home",
      isRemote: true,
      tags: ["HTML", "CSS", "JavaScript"],
    },
    {
      title: "Principal Software Engineer",
      company: "Salesforce",
      description: "Architect enterprise-grade platforms.",
      type: "Full-time",
      experience: "8+ years",
      location: "Bengaluru, Karnataka",
      isRemote: true,
      tags: ["System Design", "Leadership"],
    },
    {
      title: "Full Stack Development Intern",
      company: "Internshala",
      description: "Build end-to-end web apps.",
      type: "Internship",
      experience: "0-1 years",
      location: "Delhi NCR",
      isRemote: false,
      tags: ["React", "Node.js"],
    },
    {
      title: "Machine Learning Engineer",
      company: "Amazon",
      description: "Build ML models at scale.",
      type: "Full-time",
      experience: "3-5 years",
      location: "Hyderabad, Telangana",
      isRemote: false,
      tags: ["Python", "ML", "AWS"],
    },
    {
      title: "Frontend Developer",
      company: "Flipkart",
      description: "Build UI used by millions.",
      type: "Full-time",
      experience: "2-4 years",
      location: "Bengaluru, Karnataka",
      isRemote: false,
      tags: ["React", "Next.js"],
    },
    {
      title: "Data Science Intern",
      company: "Internshala",
      description: "Analyze datasets and build ML models.",
      type: "Internship",
      experience: "0-1 years",
      location: "Mumbai, Maharashtra",
      isRemote: false,
      tags: ["Python", "Pandas"],
    },
    {
      title: "DevOps Engineer",
      company: "Infosys",
      description: "Manage CI/CD pipelines.",
      type: "Full-time",
      experience: "3-5 years",
      location: "Pune, Maharashtra",
      isRemote: true,
      tags: ["AWS", "Docker", "Kubernetes"],
    },
    {
      title: "Android Developer",
      company: "Paytm",
      description: "Build Android applications.",
      type: "Full-time",
      experience: "2-4 years",
      location: "Noida, Uttar Pradesh",
      isRemote: false,
      tags: ["Kotlin", "Android"],
    },
    {
      title: "AI/ML Intern",
      company: "Internshala",
      description: "Work on AI projects.",
      type: "Internship",
      experience: "0-1 years",
      location: "Work From Home",
      isRemote: true,
      tags: ["Python", "ML"],
    },
    {
      title: "Backend Developer",
      company: "Swiggy",
      description: "Build scalable backend services.",
      type: "Full-time",
      experience: "3-5 years",
      location: "Bengaluru, Karnataka",
      isRemote: false,
      tags: ["Go", "Microservices"],
    },
    {
      title: "Product Manager",
      company: "Razorpay",
      description: "Own product roadmap.",
      type: "Full-time",
      experience: "4-6 years",
      location: "Bengaluru, Karnataka",
      isRemote: true,
      tags: ["Product", "Fintech"],
    },
    {
      title: "iOS Developer",
      company: "PhonePe",
      description: "Build iOS applications.",
      type: "Full-time",
      experience: "2-4 years",
      location: "Bengaluru, Karnataka",
      isRemote: false,
      tags: ["Swift", "iOS"],
    },
    {
      title: "Cloud Engineering Intern",
      company: "Internshala",
      description: "Work on cloud infrastructure.",
      type: "Internship",
      experience: "0-1 years",
      location: "Hyderabad, Telangana",
      isRemote: false,
      tags: ["AWS", "Linux"],
    },
    {
      title: "Site Reliability Engineer",
      company: "Uber",
      description: "Ensure platform reliability.",
      type: "Full-time",
      experience: "4-6 years",
      location: "Hyderabad, Telangana",
      isRemote: true,
      tags: ["SRE", "Kubernetes"],
    },
    {
      title: "UI/UX Design Intern",
      company: "Internshala",
      description: "Design UI screens.",
      type: "Internship",
      experience: "0-1 years",
      location: "Work From Home",
      isRemote: true,
      tags: ["Figma", "Design"],
    },
    {
      title: "Cybersecurity Analyst",
      company: "TCS",
      description: "Monitor security incidents.",
      type: "Full-time",
      experience: "2-4 years",
      location: "Chennai, Tamil Nadu",
      isRemote: false,
      tags: ["SOC", "SIEM"],
    },
  ];

  for (const job of jobs) {
    await prisma.job.create({ data: job });
  }

  console.log("✅ All 20 jobs seeded successfully");
  process.exit(0);
}

seedAllJobs().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
