export const jobs = [
  {
    title: "Software Developer 3",
    company: "Oracle",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "3-5 years",
    salary: "₹18L - ₹35L",
    postedAt: "Hiring now",
    tags: ["Java", "Cloud", "OCI", "Microservices"],
    isRemote: false,
    logo: "company-techflow.png",
    applyUrl: "https://www.oracle.com/corporate/careers/",
    description: "Work on enterprise-grade cloud applications and scalable backend services."
  },
  {
    title: "Senior Software Engineer",
    company: "Google",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "5+ years",
    salary: "₹35L - ₹60L",
    postedAt: "Hiring now",
    tags: ["Python", "Go", "Distributed Systems"],
    isRemote: true,
    logo: "company-cloudix.png",
    applyUrl: "https://careers.google.com/jobs/results/",
    description: "Build and maintain highly scalable distributed systems."
  },
  {
    title: "Lead Software Engineer - Backend",
    company: "Salesforce",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "5+ years",
    salary: "₹40L - ₹65L",
    postedAt: "Hiring now",
    tags: ["Java", "Scala", "AWS"],
    isRemote: true,
    logo: "company-nexgen.png",
    applyUrl: "https://careers.salesforce.com/",
    description: "Lead backend architecture and mentor engineering teams."
  },
  {
    title: "Software Development Intern",
    company: "Internshala",
    location: "Work From Home",
    type: "Internship",
    experience: "0-1 years",
    salary: "₹15K - ₹25K/month",
    postedAt: "Hiring now",
    tags: ["React", "Node.js", "MongoDB"],
    isRemote: true,
    logo: "company-datawise.png",
    applyUrl: "https://internshala.com/internships/",
    description: "Work on real-world full-stack applications under mentorship."
  },
  {
    title: "Web Development Intern",
    company: "Internshala",
    location: "Work From Home",
    type: "Internship",
    experience: "0-1 years",
    salary: "₹10K - ₹20K/month",
    postedAt: "Hiring now",
    tags: ["HTML", "CSS", "JavaScript"],
    isRemote: true,
    logo: "company-medtech.png",
    applyUrl: "https://internshala.com/internships/",
    description: "Develop responsive and user-friendly web pages."
  },
  {
    title: "Principal Software Engineer",
    company: "Salesforce",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "8+ years",
    salary: "₹50L - ₹80L",
    postedAt: "Hiring now",
    tags: ["System Design", "Leadership"],
    isRemote: true,
    logo: "company-nexgen.png",
    applyUrl: "https://careers.salesforce.com/",
    description: "Own architecture of large-scale enterprise platforms."
  },
  {
    title: "Full Stack Development Intern",
    company: "Internshala",
    location: "Delhi NCR",
    type: "Internship",
    experience: "0-1 years",
    salary: "₹15K - ₹30K/month",
    postedAt: "Hiring now",
    tags: ["React", "Node.js"],
    isRemote: false,
    logo: "company-aicore.png",
    applyUrl: "https://internshala.com/internships/",
    description: "Build complete web applications from frontend to backend."
  },
  {
    title: "Machine Learning Engineer",
    company: "Amazon",
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "3-5 years",
    salary: "₹25L - ₹45L",
    postedAt: "Hiring now",
    tags: ["Python", "ML", "AWS"],
    isRemote: false,
    logo: "company-cloudix.png",
    applyUrl: "https://www.amazon.jobs/en/",
    description: "Develop and deploy machine learning models at scale."
  },
  {
    title: "Frontend Developer",
    company: "Flipkart",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "2-4 years",
    salary: "₹18L - ₹30L",
    postedAt: "Hiring now",
    tags: ["React", "Next.js"],
    isRemote: false,
    logo: "company-techflow.png",
    applyUrl: "https://www.flipkartcareers.com/",
    description: "Build high-performance user interfaces for large platforms."
  },
  {
    title: "Data Science Intern",
    company: "Internshala",
    location: "Mumbai, Maharashtra",
    type: "Internship",
    experience: "0-1 years",
    salary: "₹20K - ₹35K/month",
    postedAt: "Hiring now",
    tags: ["Python", "Pandas"],
    isRemote: false,
    logo: "company-datawise.png",
    applyUrl: "https://internshala.com/internships/",
    description: "Analyze datasets and build basic ML models."
  },

  /* ===== JOBS 11–25 ===== */

  {
    title: "Backend Engineer",
    company: "Swiggy",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "2-4 years",
    salary: "₹20L - ₹32L",
    postedAt: "Hiring now",
    tags: ["Java", "Spring Boot"],
    isRemote: false,
    logo: "company-nexgen.png",
    applyUrl: "https://careers.swiggy.com/",
    description: "Build scalable backend systems for food delivery."
  },
  {
    title: "DevOps Engineer",
    company: "Infosys",
    location: "Pune, Maharashtra",
    type: "Full-time",
    experience: "3-6 years",
    salary: "₹12L - ₹22L",
    postedAt: "Hiring now",
    tags: ["AWS", "Docker", "CI/CD"],
    isRemote: false,
    logo: "company-techflow.png",
    applyUrl: "https://www.infosys.com/careers/",
    description: "Automate deployments and manage cloud infrastructure."
  },
  {
    title: "Android Developer",
    company: "Paytm",
    location: "Noida, Uttar Pradesh",
    type: "Full-time",
    experience: "2-4 years",
    salary: "₹15L - ₹28L",
    postedAt: "Hiring now",
    tags: ["Kotlin", "Android"],
    isRemote: false,
    logo: "company-cloudix.png",
    applyUrl: "https://paytm.com/careers/",
    description: "Develop Android apps used by millions."
  },
  {
    title: "UI/UX Designer",
    company: "Zomato",
    location: "Gurgaon, Haryana",
    type: "Full-time",
    experience: "2-5 years",
    salary: "₹12L - ₹20L",
    postedAt: "Hiring now",
    tags: ["Figma", "UX"],
    isRemote: false,
    logo: "company-medtech.png",
    applyUrl: "https://www.zomato.com/careers",
    description: "Design user-friendly food delivery experiences."
  },
  {
    title: "Cloud Support Engineer",
    company: "Microsoft",
    location: "Hyderabad, Telangana",
    type: "Full-time",
    experience: "1-3 years",
    salary: "₹14L - ₹24L",
    postedAt: "Hiring now",
    tags: ["Azure", "Linux"],
    isRemote: false,
    logo: "company-aicore.png",
    applyUrl: "https://careers.microsoft.com/",
    description: "Support enterprise customers using Azure."
  },
  {
    title: "QA Automation Engineer",
    company: "Wipro",
    location: "Chennai, Tamil Nadu",
    type: "Full-time",
    experience: "2-4 years",
    salary: "₹8L - ₹15L",
    postedAt: "Hiring now",
    tags: ["Selenium", "Testing"],
    isRemote: false,
    logo: "company-datawise.png",
    applyUrl: "https://careers.wipro.com/",
    description: "Automate test cases for enterprise applications."
  },
  {
    title: "Business Analyst",
    company: "Accenture",
    location: "Gurgaon, Haryana",
    type: "Full-time",
    experience: "2-5 years",
    salary: "₹10L - ₹18L",
    postedAt: "Hiring now",
    tags: ["Analysis", "Stakeholders"],
    isRemote: false,
    logo: "company-techflow.png",
    applyUrl: "https://www.accenture.com/careers",
    description: "Translate business requirements into technical solutions."
  },
  {
    title: "Data Engineer",
    company: "Uber",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "4-6 years",
    salary: "₹28L - ₹45L",
    postedAt: "Hiring now",
    tags: ["Spark", "Big Data"],
    isRemote: false,
    logo: "company-cloudix.png",
    applyUrl: "https://www.uber.com/careers/",
    description: "Build and maintain data pipelines at scale."
  },
  {
    title: "Product Manager",
    company: "Razorpay",
    location: "Bengaluru, Karnataka",
    type: "Full-time",
    experience: "3-6 years",
    salary: "₹20L - ₹35L",
    postedAt: "Hiring now",
    tags: ["Product", "Agile"],
    isRemote: false,
    logo: "company-nexgen.png",
    applyUrl: "https://razorpay.com/jobs/",
    description: "Own product roadmap and execution."
  },
  {
    title: "AI Research Intern",
    company: "OpenAI Labs",
    location: "Remote",
    type: "Internship",
    experience: "0-1 years",
    salary: "₹40K - ₹60K/month",
    postedAt: "Hiring now",
    tags: ["AI", "Research"],
    isRemote: true,
    logo: "company-aicore.png",
    applyUrl: "https://openai.com/careers",
    description: "Assist in AI research and experimentation."
  }
];
